name: Build And Publish Python Distribution 📦

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python with uv
        uses: drivendataorg/setup-python-uv-action@main
        with:
          python-version: 3.12
          cache: packages
          cache-dependency-path: >-
            pyproject.toml

      - name: Install the build package
        run: uv pip install build[uv]
      - name: Build the package
        run: python -m build --installer uv .
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
            name: python-package-distributions
            path: dist/

  publish-to-testpypi:
    name: Publish to TestPyPI 🐍
    needs:
      - build
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/sigmatcher

    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
